### PR TITLE
Fix mac compiling [WIP]

### LINKED ISSUE #19: macOS Catalina error installing dependency, following MacOS Build instructions doc.
When doing 
```
% brew install automake libtool pkg-config
```
the python2 dependency was said to be "broken", but the process ended with an error. macOS at least used to run Python2 built-in, but personally I always use Python 3.9.

Here is the relevant part.
```
==> Checking for dependents of upgraded formulae...
==> Reinstalling 1 broken dependent from source:
python@2
==> Downloading https://ghcr.io/v2/homebrew/core/sphinx-doc/manifests/4.2.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/sphinx-doc/blobs/sha256:60814b10d58a932560cc6fe41317e1d6ca13c68eeb6e76200470e1486b00f149
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:60814b10d58a932560cc6fe41317e1d6ca13c68eeb6e76200470e1486b00f
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/37/1b/b25507861991beeade31473868463dad0e58b1978c209de27384ae541b0b/setuptools-40.6.3.zip
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/45/ae/8a0ad77defb7cc903f09e551d88b443304a9bd6e6f124e75c0fbbf6de8f7/pip-18.1.tar.gz
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/d8/55/221a530d66bf78e72996453d1e2dedef526063546e131d70bed548d80588/wheel-0.32.3.tar.gz
######################################################################## 100.0%
==> Downloading https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tar.xz
######################################################################## 100.0%
==> Reinstalling python@2 
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 12.4.

==> Installing dependencies for python@2: sphinx-doc
==> Installing python@2 dependency: sphinx-doc
==> Pouring sphinx-doc--4.2.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/sphinx-doc/4.2.0: 3,924 files, 56MB
==> Installing python@2
Error: An exception occurred within a child process:
  FormulaUnavailableError: No available formula with the name "/usr/local/opt/python@2/.brew/python@2.rb".
```

### PR DESCRIPTION
**Pull request by KMSoftwareHQ**
Fix mac os compiling.

### CODE REVIEW

**Comment by seanPhill** [comment]
At the moment, if I do `make` in depends I still get stopped at the attempted boost 1.64 (while I already have 1.76 on my system via homebrew). I presume it then doesn't try whichever ones remain.
If I ignore that, and do `make` (in the parent directory with nothing else) I get stopped at this error
``` 
In file included from bloom.cpp:9:
In file included from ./evo/providertx.h:8:
./bls/bls.h:14:10: fatal error: 'chiabls/bls.hpp' file not found
#include <chiabls/bls.hpp>
```
(After `make clean` the `depends/x86_64-apple-darwin19.6.0` directory is clean again. Actually it's clean after the failed `make` anyway.) I'll try finding the list of dependencies and see if I can load everything manually. (I vaguely remember doing this previously, when I compiled my current macOS Genix wallet.

**Comment by seanPhill** [comment]
I see the same thing happened in the Github Actions build.
Maybe we can look at updating the boost version in `depends/packages/boost.mk`

**Comment by KMSoftwareHQ** [comment]
> I see the same thing happened in the Github Actions build.
> Maybe we can look at updating the boost version in `depends/packages/boost.mk`

will look into it.

**Comment by seanPhill** [comment]
> > I see the same thing happened in the Github Actions build.
> > Maybe we can look at updating the boost version in `depends/packages/boost.mk`
> 
> will look into it.

Cool! I also tested an updated link for 1.64 
> $(package)_download_path=https://dl.bintray.com/boostorg/release/1.64.0/source/
> $(package)_download_path=https://boostorg.jfrog.io/artifactory/main/release/1.64.0/source/

Same hash, and same failure.
the latest is 1.76 (on jfrog.io via boost.org)

**Comment by KMSoftwareHQ** [comment]
We'll see how the latest commit goes.

**Comment by KMSoftwareHQ** [comment]
Looks like it passed boost in depends 🤞

**Comment by seanPhill** [comment]
> At the moment, if I do `make` in depends I still get stopped at the attempted boost 1.64 (while I already have 1.76 on my system via homebrew). I presume it then doesn't try whichever ones remain. If I ignore that, and do `make` (in the parent directory with nothing else) I get stopped at this error
> 
> ```
> In file included from bloom.cpp:9:
> In file included from ./evo/providertx.h:8:
> ./bls/bls.h:14:10: fatal error: 'chiabls/bls.hpp' file not found
> #include <chiabls/bls.hpp>
> ```
> 
> (After `make clean` the `depends/x86_64-apple-darwin19.6.0` directory is clean again. Actually it's clean after the failed `make` anyway.) I'll try finding the list of dependencies and see if I can load everything manually. (I vaguely remember doing this previously, when I compiled my current macOS Genix wallet.

I got mostly through compiling today. I was able to upgrade boost 1.78.0_1 -> 1.79.0_1 (and many others) simply by doing 
`brew upgrade`.

I had that bloom chiabls installation problem on Linux Ubuntu 20.04 and macOS 12.4 (Monterey) today, and was able to use the same workaround.
I downloaded from this repo (https://github.com/codablock/bls-signatures/) https://github.com/codablock/bls-signatures/archive/refs/tags/v20181101.zip and extracted and ran the following.

```
mkdir build
 cd build
 cmake ../ 
make
sudo make install
```

Then I went back to the Genix repo and ran `make` again.

**Comment by seanPhill** [comment]
On my own fork I updated the boost version to 1.79 and in Github Actions got an interesting failure:
In Linux, Windows, & Mac, with different wording:
```
In file included from init.cpp:89:0:
[657](https://github.com/seanPhill/genix/runs/7671083963?check_suite_focus=true#step:6:658)
/home/runner/work/genix/genix/source/depends/x86_64-pc-linux-gnu/share/../include/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
```
This is the same _1, _2, that caused a build failure on my Mac yesterday.

Unless I can figure out what to do about these placeholders, I may have to go back to an earlier version of boost. (My Mac was compiling after having upgraded the boost dependency to 1.79.

**Pull request closed without merging**
